# Generated by Django 6.0.3 on 2026-04-11 13:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('converted', 'Converti en commande'), ('abandoned', 'Abandonné'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('redis_key', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('order_id', models.UUIDField(blank=True, help_text='FK vers orders.Order si converti', null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_sessions', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart_sessions',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(help_text="ID de l'item dans MongoDB menus", max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_options', models.JSONField(default=list)),
                ('options_extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_snapshot', models.JSONField(default=dict)),
                ('special_instructions', models.CharField(blank=True, max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartsession')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('order_id', models.UUIDField(help_text='Commande source de cette notation')),
                ('photos', models.JSONField(default=list, help_text='URLs photos du plat publiées par le client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_ratings',
            },
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, help_text='Moyenne calculée depuis item_ratings', max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('ratings_distribution', models.JSONField(default=dict, help_text="{'1': 5, '2': 3, '3': 10, '4': 25, '5': 57}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_ratings',
            },
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['user', 'status'], name='cart_sessio_user_id_2fb4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['status', 'updated_at'], name='cart_sessio_status_a71be8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item_id')},
        ),
        migrations.AddIndex(
            model_name='itemrating',
            index=models.Index(fields=['item_id'], name='item_rating_item_id_af2267_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrating',
            index=models.Index(fields=['restaurant', 'rating'], name='item_rating_restaur_e1195e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemrating',
            unique_together={('user', 'item_id', 'order_id')},
        ),
    ]
