# Generated by Django 6.0.3 on 2026-04-13 13:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalyticsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('avg_session_duration_seconds', models.PositiveIntegerField(default=0)),
                ('avg_pages_per_session', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_device', models.CharField(blank=True, max_length=20)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_order_value_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('orders_delivered', models.PositiveIntegerField(default=0)),
                ('cart_abandonments', models.PositiveIntegerField(default=0)),
                ('favorite_restaurant_id', models.UUIDField(blank=True, null=True)),
                ('favorite_restaurant_name', models.CharField(blank=True, max_length=200)),
                ('favorite_restaurant_orders', models.PositiveIntegerField(default=0)),
                ('most_active_hour', models.PositiveSmallIntegerField(blank=True, help_text="Heure 0-23 où l'utilisateur est le plus actif", null=True)),
                ('most_active_day', models.PositiveSmallIntegerField(blank=True, help_text='Jour 0=Lundi … 6=Dimanche', null=True)),
                ('orders_by_hour', models.JSONField(default=dict, help_text="{'0': 0, '12': 3, '19': 5, ...}")),
                ('orders_by_day', models.JSONField(default=dict, help_text="{'0': 2, '5': 8, ...}")),
                ('preferred_device', models.CharField(blank=True, max_length=20)),
                ('preferred_os', models.CharField(blank=True, max_length=20)),
                ('primary_city', models.CharField(blank=True, max_length=100)),
                ('primary_country', models.CharField(blank=True, max_length=100)),
                ('known_ips', models.JSONField(default=list, help_text='Liste des IP connues')),
                ('top_search_queries', models.JSONField(default=list, help_text="[{'query': 'ndolé', 'count': 12}, ...]")),
                ('top_visited_paths', models.JSONField(default=list, help_text="[{'path': '/api/v1/restaurants/', 'count': 45}, ...]")),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, help_text='Score 0-100 basé sur fréquence, dépenses et fidélité', max_digits=5)),
                ('churn_risk_score', models.DecimalField(decimal_places=2, default=0, help_text="Score 0-100 : probabilité d'abandon (basé sur inactivité)", max_digits=5)),
                ('loyalty_tier', models.CharField(choices=[('new', 'Nouveau'), ('bronze', 'Bronze'), ('silver', 'Argent'), ('gold', 'Or'), ('platinum', 'Platine')], default='new', help_text='Calculé selon total_spent_xaf et total_orders', max_length=20)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('avg_rating_given', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablette'), ('desktop', 'Desktop'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('os_version', models.CharField(blank=True, max_length=30)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=30)),
                ('user_agent', models.TextField(blank=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('page_views_count', models.PositiveIntegerField(default=0)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('is_bounce', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null si session anonyme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Vue de page'), ('search', 'Recherche'), ('filter_applied', 'Filtre appliqué'), ('restaurant_viewed', 'Restaurant consulté'), ('menu_opened', 'Menu ouvert'), ('item_viewed', 'Item consulté'), ('item_added_to_cart', 'Item ajouté au panier'), ('item_removed_from_cart', 'Item retiré du panier'), ('cart_abandoned', 'Panier abandonné'), ('order_started', 'Commande démarrée'), ('order_confirmed', 'Commande confirmée'), ('order_cancelled', 'Commande annulée'), ('order_tracking_opened', 'Tracking ouvert'), ('payment_initiated', 'Paiement initié'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('wallet_topped_up', 'Wallet rechargé'), ('review_started', 'Review démarrée'), ('review_submitted', 'Review soumise'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('register', 'Inscription'), ('profile_updated', 'Profil mis à jour'), ('address_added', 'Adresse ajoutée'), ('error_404', 'Page introuvable'), ('error_500', 'Erreur serveur'), ('error_auth', "Erreur d'authentification"), ('error_payment', 'Erreur paiement')], db_index=True, max_length=50)),
                ('object_type', models.CharField(blank=True, help_text="Ex: 'order', 'restaurant', 'menu_item'", max_length=50)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Données contextuelles libres : prix, nom plat, restaurant_id, query, etc.')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.usersession')),
            ],
            options={
                'db_table': 'analytics_events',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('query_normalized', models.CharField(db_index=True, help_text='Minuscules, trimé', max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_result_id', models.CharField(blank=True, max_length=100)),
                ('clicked_result_type', models.CharField(blank=True, max_length=50)),
                ('filters_applied', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='analytics.usersession')),
            ],
            options={
                'db_table': 'analytics_searches',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('query_string', models.TextField(blank=True)),
                ('full_url', models.TextField(blank=True)),
                ('http_status', models.PositiveSmallIntegerField(db_index=True)),
                ('response_time_ms', models.PositiveIntegerField(help_text='Temps de réponse en millisecondes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('view_name', models.CharField(blank=True, help_text='Nom Django de la vue', max_length=200)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.usersession')),
            ],
            options={
                'db_table': 'analytics_pageviews',
            },
        ),
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_id', models.UUIDField(blank=True, null=True)),
                ('restaurant_name', models.CharField(blank=True, max_length=200)),
                ('last_step', models.PositiveSmallIntegerField(choices=[(1, 'restaurant_viewed'), (2, 'menu_opened'), (3, 'item_added_to_cart'), (4, 'order_started'), (5, 'payment_initiated'), (6, 'order_confirmed')], default=1)),
                ('last_step_name', models.CharField(blank=True, max_length=50)),
                ('converted', models.BooleanField(db_index=True, default=False)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('step_timestamps', models.JSONField(default=dict, help_text="{'restaurant_viewed': '...', 'menu_opened': '...', ...}")),
                ('time_to_convert_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('abandoned_at_step', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abandon_reason', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnels', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to='analytics.usersession')),
            ],
            options={
                'db_table': 'analytics_funnels',
            },
        ),
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_tags', models.JSONField(default=list)),
                ('top_item_ids', models.JSONField(default=list, help_text='IDs MongoDB des items préférés')),
                ('avoided_item_ids', models.JSONField(default=list)),
                ('restaurant_scores', models.JSONField(default=dict, help_text="{'restaurant_uuid': 42, ...}")),
                ('avg_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_comfortable_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frequent_options', models.JSONField(default=list, help_text="[{'label': 'Extra sauce', 'frequency': 12}, ...]")),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_taste_profiles',
            },
        ),
        migrations.CreateModel(
            name='BehavioralAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('multiple_failed_payments', 'Plusieurs paiements échoués'), ('unusual_location', 'Connexion depuis emplacement inhabituel'), ('high_cart_abandonment', "Taux d'abandon panier élevé"), ('inactive_user', 'Utilisateur inactif 30+ jours'), ('high_cancellation_rate', "Taux d'annulation élevé"), ('suspicious_activity', 'Activité suspecte (trop de requêtes)'), ('multiple_accounts_same_ip', 'Plusieurs comptes depuis même IP'), ('churn_risk', 'Risque de départ détecté')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_alerts',
                'indexes': [models.Index(fields=['user', 'alert_type'], name='analytics_a_user_id_0c93f9_idx'), models.Index(fields=['is_resolved', 'created_at'], name='analytics_a_is_reso_da093e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(db_index=True, help_text="ID MongoDB de l'item", max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('restaurant_id', models.UUIDField(db_index=True)),
                ('interaction_type', models.CharField(choices=[('viewed', 'Vu'), ('detail_opened', 'Détail ouvert'), ('added_to_cart', 'Ajouté au panier'), ('removed_from_cart', 'Retiré du panier'), ('ordered', 'Commandé'), ('rated_positive', 'Note positive (4-5)'), ('rated_negative', 'Note négative (1-2)'), ('shared', 'Partagé')], db_index=True, max_length=30)),
                ('item_tags', models.JSONField(default=list)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selected_options', models.JSONField(default=list)),
                ('weight', models.SmallIntegerField(default=1, help_text="Poids de l'interaction")),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_item_interactions',
                'indexes': [models.Index(fields=['user', 'item_id'], name='analytics_i_user_id_0f5ba4_idx'), models.Index(fields=['user', 'interaction_type', 'timestamp'], name='analytics_i_user_id_e65427_idx'), models.Index(fields=['item_id', 'interaction_type'], name='analytics_i_item_id_ae9e33_idx'), models.Index(fields=['restaurant_id', 'interaction_type'], name='analytics_i_restaur_cfaabd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'started_at'], name='analytics_s_user_id_89d06e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address'], name='analytics_s_ip_addr_0e8744_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['device_type'], name='analytics_s_device__68441f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['country'], name='analytics_s_country_1b454f_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', 'event_type', 'timestamp'], name='analytics_e_user_id_820d58_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_e_event_t_5b2eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['object_type', 'object_id'], name='analytics_e_object__35a664_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query_normalized'], name='analytics_s_query_n_91bc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_s_user_id_1fa64e_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_p_user_id_f74e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path', 'timestamp'], name='analytics_p_path_322790_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['http_status'], name='analytics_p_http_st_76f45f_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['timestamp'], name='analytics_p_timesta_b268ac_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionfunnel',
            index=models.Index(fields=['user', 'started_at'], name='analytics_f_user_id_98968e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionfunnel',
            index=models.Index(fields=['converted'], name='analytics_f_convert_ad2111_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionfunnel',
            index=models.Index(fields=['restaurant_id'], name='analytics_f_restaur_c19ffd_idx'),
        ),
    ]
